# Generated by Django 4.2.30 on 2026-07-11 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('running', 'Running'), ('finished', 'Finished')], default='draft', max_length=20)),
                ('vm_spec', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-exam_time'],
            },
        ),
        migrations.CreateModel(
            name='VmGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_group_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_groups', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VM Group',
                'verbose_name_plural': 'VM Groups',
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='VmInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_type', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux')], max_length=20)),
                ('role_label', models.CharField(blank=True, max_length=100)),
                ('cpu', models.IntegerField(default=2)),
                ('ram', models.IntegerField(default=4)),
                ('disk', models.IntegerField(default=50)),
                ('image_id', models.CharField(blank=True, max_length=100)),
                ('cvm_instance_id', models.CharField(blank=True, max_length=100)),
                ('private_ip', models.CharField(blank=True, max_length=50)),
                ('admin_username', models.CharField(default='Administrator', max_length=100)),
                ('admin_password', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('terminated', 'Terminated')], default='creating', max_length=20)),
                ('guacamole_connection_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='exams.vmgroup')),
            ],
            options={
                'verbose_name': 'VM Instance',
                'verbose_name_plural': 'VM Instances',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(through='exams.VmGroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
